// packages/vue/src/components/SecLabFormItem.vue
<script setup lang="ts">
import { computed, useId } from "vue";

/**
 * @file SecLabFormItem.vue
 * @description SecLab 平台自研表单项组件，处理标签和布局。
 */

interface Props {
  /** 标签文本 */
  label?: string;
  /** 是否必填 (显示红星) */
  required?: boolean;
  /** 提示文本 */
  hint?: string;
  for?: string;
  error?: string;
  labelId?: string;
  hintId?: string;
  errorId?: string;
}

const props = defineProps<Props>();
const generatedId = useId();
const resolvedLabelId = computed(() => props.labelId ?? `${generatedId}-label`);
const resolvedHintId = computed(() => props.hintId ?? `${generatedId}-hint`);
const resolvedErrorId = computed(() => props.errorId ?? `${generatedId}-error`);
</script>

<template>
  <div class="sl-form-item">
    <label
      v-if="label"
      :id="resolvedLabelId"
      class="sl-form-item-label"
      :for="for"
    >
      <span v-if="required" class="sl-form-item-required">*</span>
      {{ label }}
    </label>
    <div class="sl-form-item-content">
      <slot></slot>
      <div v-if="hint" :id="resolvedHintId" class="sl-form-item-hint">
        {{ hint }}
      </div>
      <div
        v-if="error"
        :id="resolvedErrorId"
        class="sl-form-item-error"
        role="alert"
      >
        {{ error }}
      </div>
    </div>
  </div>
</template>

<style scoped>
.sl-form-item {
  margin-bottom: var(--sdl-space-4);
  display: flex;
  flex-direction: column;
  gap: var(--sdl-space-2);
}

.sl-form-item-label {
  font-size: var(--sdl-font-body-sm);
  font-weight: 600;
  color: var(--sdl-text-secondary);
  line-height: 1.4;
  user-select: none;
}

.sl-form-item-required {
  color: var(--sdl-danger);
  margin-right: 4px;
}

.sl-form-item-content {
  position: relative;
  width: 100%;
}

.sl-form-item-hint {
  margin-top: var(--sdl-space-1);
  font-size: var(--sdl-font-caption);
  color: var(--sdl-text-muted);
  line-height: 1.4;
}
.sl-form-item-error {
  margin-top: var(--sdl-space-1);
  color: var(--sdl-danger);
  font-size: var(--sdl-font-caption);
}
</style>

// packages/react/src/components/SecLabFormItem/SecLabFormItem.tsx
import React, { useId } from "react";
import "./SecLabFormItem.css";

export interface SecLabFormItemProps extends React.HTMLAttributes<HTMLDivElement> {
  /** 标签文本 */
  label?: string;
  /** 是否必填 (显示红星) */
  required?: boolean;
  /** 提示文本 */
  hint?: string;
  htmlFor?: string;
  error?: string;
  labelId?: string;
  hintId?: string;
  errorId?: string;
}

export const SecLabFormItem: React.FC<SecLabFormItemProps> = ({
  label,
  required = false,
  hint,
  htmlFor,
  error,
  labelId,
  hintId,
  errorId,
  className = "",
  children,
  ...rest
}) => {
  const generatedId = useId();
  const resolvedLabelId = labelId ?? `${generatedId}-label`;
  const resolvedHintId = hintId ?? `${generatedId}-hint`;
  const resolvedErrorId = errorId ?? `${generatedId}-error`;

  return (
    <div className={`sl-form-item ${className}`.trim()} {...rest}>
      {label && (
        <label
          id={resolvedLabelId}
          className="sl-form-item-label"
          htmlFor={htmlFor}
        >
          {required && <span className="sl-form-item-required">*</span>}
          {label}
        </label>
      )}
      <div className="sl-form-item-content">
        {children}
        {hint && (
          <div id={resolvedHintId} className="sl-form-item-hint">
            {hint}
          </div>
        )}
        {error && (
          <div id={resolvedErrorId} className="sl-form-item-error" role="alert">
            {error}
          </div>
        )}
      </div>
    </div>
  );
};
